
import type { Job } from "./types";

export const MOCK_JOBS: Job[] = [
  {
    id: "pt-itjobs-505769",
    titulo: "Administrador de Sistemas (Azure)",
    empresa: "ExemploTech",
    pais: "Portugal",
    cidade: "Lisboa",
    modalidade: "Híbrido",
    contrato: "Efetivo",
    salario: null,
    descricao: "Planejar, implementar e manter infra Azure. Monitorização e automação.",
    pre_requisitos: ["Azure", "PowerShell", "Inglês intermediário"],
    data_publicacao: "2025-11-07",
    data_coleta: new Date().toISOString(),
    status_vaga: "ativa",
    fonte: "ITJobs.pt",
    link_candidatura: "https://www.itjobs.pt/oferta/505769/administrador-de-sistemas-azure",
    link_canonico: "https://www.itjobs.pt/oferta/505769/administrador-de-sistemas-azure",
    link_tipo: "portal_final",
    link_status: "OK",
    compartilhar_whatsapp: "",
    atendimento_site: "https://www.dnvturismo.com.br",
    instagram: "https://www.instagram.com/dnvturismo?igsh=MXMyOTUwbGozZHA4Zw==",
    whatsapp_atendimento: "https://wa.me/message/VWCYVUQICMY3B1"
  },
  {
    id: "es-greenhouse-1234567",
    titulo: "Atendimento ao Cliente (Português/Espanhol)",
    empresa: "Global Support SL",
    pais: "Espanha",
    cidade: "Barcelona",
    modalidade: "Híbrido",
    contrato: "Efetivo",
    salario: "EUR 1.400–1.700/mês",
    descricao: "Atendimento multicanal a clientes lusófonos e hispanohablantes.",
    pre_requisitos: ["PT fluente", "ES avançado", "Experiência com CRM"],
    data_publicacao: "2025-11-07",
    data_coleta: new Date().toISOString(),
    status_vaga: "ativa",
    fonte: "Greenhouse",
    link_candidatura: "https://jobs.greenhouse.io/globalsupport/jobs/1234567",
    link_canonico: "https://jobs.greenhouse.io/globalsupport/jobs/1234567",
    link_tipo: "ats",
    link_status: "OK",
    compartilhar_whatsapp: "",
    atendimento_site: "https://www.dnvturismo.com.br",
    instagram: "https://www.instagram.com/dnvturismo?igsh=MXMyOTUwbGozZHA4Zw==",
    whatsapp_atendimento: "https://wa.me/message/VWCYVUQICMY3B1"
  },
  {
    id: "pt-workday-abcde",
    titulo: "Analista de Dados",
    empresa: "DataCorp PT",
    pais: "Portugal",
    cidade: "Porto",
    modalidade: "Remoto",
    contrato: "Efetivo",
    salario: "EUR 2.000–2.500/mês",
    descricao: "Análise e modelagem de dados, criação de dashboards.",
    pre_requisitos: ["SQL", "Python", "Power BI/Tableau"],
    data_publicacao: "2025-11-06",
    data_coleta: new Date().toISOString(),
    status_vaga: "ativa",
    fonte: "Workday",
    link_candidatura: "https://careers.datacorp.com/wday/careers/job/abcde",
    link_canonico: "https://careers.datacorp.com/wday/careers/job/abcde",
    link_tipo: "ats",
    link_status: "OK",
    compartilhar_whatsapp: "",
    atendimento_site: "https://www.dnvturismo.com.br",
    instagram: "https://www.instagram.com/dnvturismo?igsh=MXMyOTUwbGozZHA4Zw==",
    whatsapp_atendimento: "https://wa.me/message/VWCYVUQICMY3B1"
  }
];
